# Generated by Django 5.2.6 on 2025-09-10 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75, verbose_name='título')),
                ('description', models.CharField(max_length=75, verbose_name='descrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categoria de despesa',
                'verbose_name_plural': 'categorias de despesas',
            },
        ),
        migrations.CreateModel(
            name='ItemDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('date', models.DateField(help_text='dia que a despesa foi gerada', verbose_name='dia')),
                ('time', models.TimeField(blank=True, help_text='hora que a despesa foi gerada (opcional)', null=True, verbose_name='hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_despesas', to='core.categoriadespesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item de despesa',
                'verbose_name_plural': 'itens de despesa',
            },
        ),
    ]
