# Generated by Django 5.2.6 on 2026-07-22 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadespesa',
            options={'ordering': ['title'], 'verbose_name': 'categoria de despesa', 'verbose_name_plural': 'categorias de despesas'},
        ),
        migrations.RenameField(
            model_name='categoriadespesa',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='categoriadespesa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemdespesa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em'),
        ),
    ]
